import Mathlib.Algebra.BigOperators.Ring.Finset
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.Positivity
import Mathlib.Tactic.Ring
import Mathlib.Tactic.Cases

/-!
# The shifting lemma for a fixed integer matrix

For a matrix `A` with natural entries (rows `ι`, columns `κ`) and a set `T` of columns, `Dep A T`
says that some nonzero integer vector supported in `T` is in the kernel of `A`.  `KernelBound A K`
says that every dependent set carries such a vector with all entries of absolute value `< K`.

* `shift`: if `K` is a kernel bound then every `z ∈ ℕ^κ` can be replaced by `z'` with `A z' = A z`
  whose set of large coordinates `{j | K ≤ z' j}` is independent.
* `monoid_iff`: the decision theorem for the monoid generated by the columns of `A`.
-/

namespace Lax117284Proofs.IlpClients

open Finset

variable {ι κ : Type*}

/-- `v` is in the (integer) kernel of `A`. -/
def IsKer [Fintype κ] (A : ι → κ → ℕ) (v : κ → ℤ) : Prop :=
  ∀ i, ∑ j, (A i j : ℤ) * v j = 0

/-- The column set `T` is dependent: a nonzero integer kernel vector is supported in `T`. -/
def Dep [Fintype κ] (A : ι → κ → ℕ) (T : Set κ) : Prop :=
  ∃ v : κ → ℤ, v ≠ 0 ∧ (∀ j, j ∉ T → v j = 0) ∧ IsKer A v

/-- Every dependent set carries a nonzero kernel vector with all entries below `K`. -/
def KernelBound [Fintype κ] (A : ι → κ → ℕ) (K : ℕ) : Prop :=
  ∀ T : Set κ, Dep A T → ∃ v : κ → ℤ, v ≠ 0 ∧ (∀ j, j ∉ T → v j = 0) ∧ IsKer A v ∧
    ∀ j, |v j| < K

theorem Dep.mono [Fintype κ] {A : ι → κ → ℕ} {T T' : Set κ} (h : T ⊆ T') (hd : Dep A T) :
    Dep A T' := by
  obtain ⟨v, hv0, hvs, hvk⟩ := hd
  exact ⟨v, hv0, fun j hj => hvs j fun hj' => hj (h hj'), hvk⟩

/-- A kernel vector with a positive entry (replace `v` by `-v` if needed). -/
theorem exists_pos_ker [Fintype κ] {A : ι → κ → ℕ} {T : Set κ} {K : ℕ}
    (h : ∃ v : κ → ℤ, v ≠ 0 ∧ (∀ j, j ∉ T → v j = 0) ∧ IsKer A v ∧ ∀ j, |v j| < K) :
    ∃ v : κ → ℤ, v ≠ 0 ∧ (∀ j, j ∉ T → v j = 0) ∧ IsKer A v ∧ (∀ j, |v j| < K) ∧
      ∃ j, 0 < v j := by
  obtain ⟨v, hv0, hvs, hvk, hvb⟩ := h
  obtain ⟨j, hj⟩ : ∃ j, v j ≠ 0 := by
    by_contra hcon
    exact hv0 (funext fun j => by by_contra h; exact hcon ⟨j, h⟩)
  rcases lt_or_gt_of_ne hj with hneg | hpos
  · refine ⟨-v, ?_, ?_, ?_, ?_, j, by simpa using hneg⟩
    · intro h0
      apply hv0
      have := congrArg Neg.neg h0
      simpa using this
    · intro j hj; simp [hvs j hj]
    · intro i
      have := hvk i
      simp only [Pi.neg_apply, mul_neg, Finset.sum_neg_distrib, this, neg_zero]
    · intro j; simpa using hvb j
  · exact ⟨v, hv0, hvs, hvk, hvb, j, hpos⟩

section Shift

variable [Fintype κ] {A : ι → κ → ℕ} {K : ℕ}

/-- One shifting step: subtract `t • v` for the largest admissible `t`.  The result is a natural
vector with the same image whose large set is strictly smaller. -/
theorem shift_step (z : κ → ℕ) (v : κ → ℤ) (hvs : ∀ j, j ∉ {j | K ≤ z j} → v j = 0)
    (hvk : IsKer A v) (hvb : ∀ j, |v j| < K) (hpos : ∃ j, 0 < v j) :
    ∃ z' : κ → ℕ, (∀ i, ∑ j, A i j * z' j = ∑ j, A i j * z j) ∧
      (univ.filter (fun j => K ≤ z' j)).card < (univ.filter (fun j => K ≤ z j)).card := by
  classical
  obtain ⟨j0, hj0⟩ := hpos
  have hne : (univ.filter (fun j => 0 < v j)).Nonempty := ⟨j0, by simp [hj0]⟩
  obtain ⟨j1, hj1, hmin⟩ := Finset.exists_min_image _ (fun j => z j / (v j).toNat) hne
  have hj1pos : 0 < v j1 := by simpa using hj1
  set t : ℕ := z j1 / (v j1).toNat with ht
  -- the integer vector
  have hnn : ∀ j, 0 ≤ (z j : ℤ) - t * v j := by
    intro j
    by_cases hj : 0 < v j
    · have h1 : t ≤ z j / (v j).toNat := hmin j (by simpa using hj)
      have h2 : t * (v j).toNat ≤ z j :=
        (Nat.mul_le_mul_right _ h1).trans (Nat.div_mul_le_self _ _)
      have h3 : ((v j).toNat : ℤ) = v j := Int.toNat_of_nonneg hj.le
      have : (t : ℤ) * v j ≤ z j := by rw [← h3]; exact_mod_cast h2
      linarith
    · have : v j ≤ 0 := not_lt.mp hj
      have : (0 : ℤ) ≤ t * (-(v j)) := mul_nonneg (by positivity) (by linarith)
      nlinarith [(Int.natCast_nonneg (z j))]
  refine ⟨fun j => ((z j : ℤ) - t * v j).toNat, ?_, ?_⟩
  · intro i
    have hcast : ∀ j, (((z j : ℤ) - t * v j).toNat : ℤ) = (z j : ℤ) - t * v j :=
      fun j => Int.toNat_of_nonneg (hnn j)
    apply Nat.cast_injective (R := ℤ)
    push_cast
    simp_rw [hcast]
    have := hvk i
    calc ∑ j, (A i j : ℤ) * ((z j : ℤ) - t * v j)
        = ∑ j, (A i j : ℤ) * z j - t * ∑ j, (A i j : ℤ) * v j := by
          rw [Finset.mul_sum, ← Finset.sum_sub_distrib]
          refine Finset.sum_congr rfl fun j _ => by ring
      _ = ∑ j, (A i j : ℤ) * z j := by rw [this]; ring
  · have hcast : ∀ j, (((z j : ℤ) - t * v j).toNat : ℤ) = (z j : ℤ) - t * v j :=
      fun j => Int.toNat_of_nonneg (hnn j)
    apply Finset.card_lt_card
    rw [Finset.ssubset_iff_of_subset]
    · refine ⟨j1, ?_, ?_⟩
      · -- j1 is large: v j1 ≠ 0 lies in the support
        simp only [mem_filter, mem_univ, true_and]
        by_contra hcon
        have := hvs j1 (by simpa using hcon)
        omega
      · simp only [mem_filter, mem_univ, true_and, not_le]
        have h3 : ((v j1).toNat : ℤ) = v j1 := Int.toNat_of_nonneg hj1pos.le
        have hlt : ((z j1 : ℤ) - t * v j1) < K := by
          have hmod : (z j1 : ℤ) - t * v j1 = ((z j1 % (v j1).toNat : ℕ) : ℤ) := by
            have := Nat.mod_add_div (z j1) (v j1).toNat
            have h4 : (z j1 : ℤ) = ((z j1 % (v j1).toNat : ℕ) : ℤ) + (v j1).toNat * t := by
              rw [ht]; exact_mod_cast this.symm
            rw [h4, h3]; ring
          have hlt2 : z j1 % (v j1).toNat < (v j1).toNat :=
            Nat.mod_lt _ (by omega)
          have := hvb j1
          rw [abs_of_pos hj1pos] at this
          rw [hmod]
          have : ((z j1 % (v j1).toNat : ℕ) : ℤ) < (v j1).toNat := by exact_mod_cast hlt2
          linarith
        have := hcast j1
        omega
    · intro j hj
      simp only [mem_filter, mem_univ, true_and] at hj ⊢
      by_cases hv : v j = 0
      · simpa [hv] using hj
      · by_contra hcon
        exact hv (hvs j (by simpa using hcon))

/-- **Shifting lemma.** -/
theorem shift (hK : KernelBound A K) (z : κ → ℕ) :
    ∃ z' : κ → ℕ, (∀ i, ∑ j, A i j * z' j = ∑ j, A i j * z j) ∧ ¬ Dep A {j | K ≤ z' j} := by
  classical
  induction' hn : (univ.filter (fun j => K ≤ z j)).card using Nat.strong_induction_on with n ih
    generalizing z
  by_cases hd : Dep A {j | K ≤ z j}
  · obtain ⟨v, hv0, hvs, hvk, hvb, hpos⟩ := exists_pos_ker (hK _ hd)
    obtain ⟨z1, hz1, hlt⟩ := shift_step z v hvs hvk hvb hpos
    obtain ⟨z', hz', hnd⟩ := ih _ (hn ▸ hlt) z1 rfl
    exact ⟨z', fun i => (hz' i).trans (hz1 i), hnd⟩
  · exact ⟨z, fun _ => rfl, hd⟩

/-- **Decision theorem.** `b` is in the monoid generated by the columns of `A` if and only if it is
`A (s + w)` for an independent column set `S`, a vector `s` supported off `S` with all entries `< K`
and a vector `w` supported on `S`. -/
theorem monoid_iff (hK : KernelBound A K) (b : ι → ℕ) :
    (∃ z : κ → ℕ, ∀ i, ∑ j, A i j * z j = b i) ↔
      ∃ S : Set κ, ¬ Dep A S ∧ ∃ s w : κ → ℕ, (∀ j, j ∈ S → s j = 0) ∧ (∀ j, j ∉ S → s j < K) ∧
        (∀ j, j ∉ S → w j = 0) ∧ ∀ i, ∑ j, A i j * (s j + w j) = b i := by
  constructor
  · rintro ⟨z, hz⟩
    obtain ⟨z', hz', hnd⟩ := shift hK z
    refine ⟨{j | K ≤ z' j}, hnd, fun j => if K ≤ z' j then 0 else z' j,
      fun j => if K ≤ z' j then z' j else 0, ?_, ?_, ?_, ?_⟩
    · intro j hj
      have : K ≤ z' j := hj
      simp [this]
    · intro j hj
      have : ¬ K ≤ z' j := hj
      show (if K ≤ z' j then 0 else z' j) < K
      rw [if_neg this]; exact not_le.mp this
    · intro j hj
      have : ¬ K ≤ z' j := hj
      simp [this]
    · intro i
      rw [← hz i, ← hz' i]
      refine Finset.sum_congr rfl fun j _ => ?_
      by_cases h : K ≤ z' j <;> simp [h]
  · rintro ⟨S, -, s, w, -, -, -, h⟩
    exact ⟨fun j => s j + w j, h⟩

end Shift

end Lax117284Proofs.IlpClients
